server:
  port: 11061

spring:
  application:
    name: cloud-stream-consumer1
  rabbitmq:
    host: 192.168.101.135
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    publisher-returns: true   #开启 return 确认机制
    publisher-confirm-type: correlated #return 确认机制类型
    template:
      mandatory: true #设置为true后消费者在消息没有被路由到合适队列情况下会被return监听，而不会自动删除

  #中间cloud部分和8802一样
  cloud:
    stream:
      function: #必须有
        definition: order;sms;cluster;broadcast;delayed

      bindings:
        order-in-0:
          destination: mq.order
        sms-in-0:
          destination: mq.sms

        #普通消息
        cluster-in-0:
          destination: cluster-topic
          group: cluster-group

        #广播消息
        broadcast-in-0:
          destination: broadcast-topic

        delayed-in-0:
          destination: delayed