server:
  port: 8082
spring:
  application:
    name: nacos-gateway-server-order
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
        username: nacos
        password: nacos
