server:
  port: 8803
spring:
  application:
    name: cloud-stream-consumer2
  #中间cloud部分和8802一样
  cloud:
    stream:
      binders: #自此处配置要绑定的rabbitmq的服务信息
        my-binder: #表示定义的名称，用于binding整合
          type: rabbit #消息组件类型
          environment: # 设置rabbitmq的相关的环境配置 stream3.1只需要配置这些即可
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: admin
                password: 123456
                virtual-host: my_vhost
      function:
        definition: order;sms
        bindings:
          order-in-0:
            destination: mq.order
          sms-in-0:
            destination: mq.sms