server:
  port: 12235
spring:
  application:
    name: a35-flowable
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hadoop102:3306/flowable-ui?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&&zeroDateTimeBehavior=CONVERT_TO_NULL&&serverTimezone=GMT%2B8&&nullCatalogMeansCurrent=true
    username: root
    password: 123456


# 7没有ui
flowable:
  #关闭定时任务JOB
  async-executor-activate: false
  # 库与数据库表今儿个不一致时,自动升级新版本
  database-schema-update: true
#  idm:
#    enabled: true
#    app:
#      admin:
#        user-id: admin
#        password: 123456



