server:
  port: 6700
spring:
  application:
    name: mall-gateway-app
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      routes: #走nacos
#        - id: mall-order-app
#          uri: lb://mall-order-app
#          predicates:
#            - Path=/order/**
#
#        - id: mall-payment-app
#          uri: lb://mall-payment-app
#          predicates:
#            - Path=/payment/**


  zipkin:
    base-url: http://192.168.101.135:9411/
    sender:
      type: web
  sleuth:
    sampler:
      #抽样百分比，默认10%的数据发到zipkin，1为100%
      probability: 1
