server:
  port: 11011
  servlet:
    context-path: /
spring:
  profiles:
    include:
      swagger
  application:
    name: minio-demo

axing:
  response:
    base-packages: com.github.axinger
  minio:
    url: http://192.168.101.143:9000
    username: admin #访问的key
    password: 12345678 #访问的秘钥

