server:
  port: 11011
  servlet:
    context-path: /
spring:
  profiles:
    include:
      swagger
  application:
    name: minio-demo

axing:
  response:
    base-packages: com.axing.demo
  minio:
    url: http://localhost:9000
    access-key: admin #访问的key
    secret-key: 12345678 #访问的秘钥

