server:
  port: 11011
  servlet:
    context-path: /
spring:
  profiles:
    include:
      swagger
  application:
    name: minio-demo

axinger:
  response:
    base-packages: com.github.axinger
  minio:
    url: http://hadoop102:19000
    username: admin #访问的key
    password: admin123 #访问的秘钥

