server:
  servlet:
    context-path: /
  port: 12009

elasticsearch:
  schema: http
  address: 192.168.101.143 #你的服务器地址
  port: 9200
  connect-timeout: 5000
  socket-timeout: 5000
  connection-request-timeout: 5000
  max-connect-num: 100
  max-connect-per-route: 100
  username: elastic
  password: 123456
