server:
  port: 8082
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ea6b039bae84c2ea97c6
            client-secret: e07ed50fc5be27fed99aeb0299b1850ac830d350



