version: 1.0.0
server:
  port: 12121

spring:
  application:
    version: 2.0.1
    description: 生产环境

axing:
  config:
    username: jim
    password: 1234
  person:
    id: 1

show:
  # 湿度
  humidity:
    min: 40.0
    max: 65.0
  # 温度
  temperature:
    min: 150
    max: 300



