dubbo:
  #  scan:
  #    base-packages: com.ax.dubbo.consumer
  application:
    name: dubbo-test-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
    username: nacos
    password: nacos
#  config-center:
#    address: nacos://localhost:8848
#    username: nacos
#    password: nacos
#    group: dubbo
#  metadata-report:
#    address: nacos://localhost:8848
#    username: nacos
#    password: nacos
#    group: dubbo

server:
  port: 7091
spring:
  application:
    name: a07-spring-cloud-alibaba-dubbo-consumer
  cloud:

    nacos:
      discovery:
        server-addr: http://localhost:8848
        password: nacos
        username: nacos

#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
#        password: nacos
#        username: nacos
#dubbo:
#  application:
#    name: dubbo-test-provider
#  registry:
#    address: nacos://127.0.0.1:8848
#  protocol:
#    name: dubbo
#    port: 20880
#  consumer:
#    timeout: 10000
