#server.port=8080
## influxDB
#spring.influx.url=http://47.101.156.93:8086
#spring.influx.user=admin
#spring.influx.password=12345678
#spring.influx.database=my_sensor1

spring:
  influx:
    url: http://47.101.156.93:8086
    user: admin
    password: 12345678
    database: ax_demo_001
