server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
#  rabbitmq:
#    host: localhost
#    port: 5672  #mq调用的端口为5672
#    username: admin
#    password: 123456
#    virtual-host: my_vhost

  #中间cloud部分和8802一样
  cloud:
    stream:
      binders: #自此处配置要绑定的rabbitmq的服务信息
        msn-binder: #表示定义的名称，用于binding整合
          type: rabbit #消息组件类型
          environment: # 设置rabbitmq的相关的环境配置 stream3.1只需要配置这些即可
            spring:
              rabbitmq:
                host: localhost
                port: 5672  #mq调用的端口为5672
                username: admin
                password: 123456
                virtual-host: my_vhost

      function:
        definition: order;sms
      bindings:
#        transfer-in-0:
#          destination: test1
#        transfer-out-0:
#          destination: test2
        #消息消费者，则需要定义为[函数对象名]-in-0。其中in表示这是一个不断接收消息的消费者
        order-in-0:
          destination: mq.order
#        order-in-1:
#          destination: mq.order
        sms-in-0:
          destination: mq.sms

#        order:
#          destination: mq.order