spring:
  profiles:
    active: dev
  aop:
    proxy-target-class: true

sms:
  threadpool:
    corePoolSize: 5 #核心线程数
    maxPoolSize: 10 #最大线程数
    keepAliveSeconds: 60 #空闲线程存活时间
    queueCapacity: 10 #等待队列长度

