server:
  port: 6700
spring:
  application:
    name: nacos-gateway-main
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: nacos-order
          uri: lb://demo07-nacos-order
          predicates:
            - Path=/order/**

        - id: nacos-payment
          uri: lb://demo07-nacos-payment
          predicates:
            - Path=/payment/**


