server:
  servlet:
    context-path: /
    encoding:
      force: true
      charset: utf-8
      enabled: true
  port: 8072

spring:
  application:
    name: demo13spring-cloud-alibaba-seata-account
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/seata_account?characterEncoding=utf-8&useSSL=false

  cloud:
#    alibaba:
#      seata:
#        tx-service-group: ax_tx_group
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

feign:
  hystrix:
    enabled: false


mybatis:
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.ax.seata.mapper

seata:
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      application: seata-server
      username: nacos
      password: nacos
      group: SEATA_GROUP