#jodconverter:
#  local:
#    enabled: true
#    max-tasks-per-process: 10
#    port-numbers: 8100
##    officeHome: D:\Program Files\LibreOffice

#jodconverter:
#  local:
#    enabled: true
#    # libreOffice根目录
#    officeHome: src/main/resources/office-plugin
#    # 任务执行的超时时间
#    taskExecutionTimeout: 86400000
#    # 任务队列的超时时间
#    taskQueueTimeout: 86400000
#    # 端口（线程）
#    portNumbers: [2001,2002,2003]
#    # 一个进程的超时时间
#    processTimeout: 86400000

jodconverter:
  local:
    enabled: true
    # 设置LibreOffice主目录
    #    office-home: /opt/libreoffice6.4
    office-home: C:/Program Files/LibreOffice
#    # 开启多个LibreOffice进程，每个端口对应一个进程
#    portNumbers: 9080,9081,9089
#    # LibreOffice进程重启前的最大进程数
#    maxTasksPerProcess: 100
