server:
  port: 12033

spring:
  profiles:
    active: dev
  web:
    resources:
      #      static-locations: "classpath:/dist"
      add-mappings: false
axinger:
  doc:
    title: docker打包项目
    description: docker打包项目
    version: @version@



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml
