server:
  port: 12033

spring:
  profiles:
    active: dev
  web:
    resources:
#      static-locations: "classpath:/dist"
      add-mappings: false
axing:
  axing:
    doc:
      title: docker打包项目
      description: docker打包项目
      version: @version@



