server:

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ax_shop?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 12345678
