server:
  port: 9003
  servlet:
    context-path: /payment

spring:
  application:
    name: mall-payment-app
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.101.135:8848
        namespace: axing-mall-dev
  zipkin:
    base-url: http://192.168.101.135:9411/
    sender:
      type: web
  sleuth:
    sampler:
      #抽样百分比，默认10%的数据发到zipkin，1为100%
      probability: 1
