spring:
  datasource:
    #    url: jdbc:h2:mem:ax_test4;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    #    url: jdbc:h2:file:~/data/databases/ax_test4;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:file:./data/databases/ax_test4;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

axinger:
  tenant:
    # 是否开启租户模式
    enable: true
    # 需要排除的多租户的表
    exclusionTable:
      - "t_sys_district"
      - "oauth_client_details"
    # 租户字段名称
    column: tenant_id
