server:
  port: 8091

spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: / #虚拟机
    username: admin
    password: admin
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true #抵达队列,异步优先执行回调
