server:
  servlet:
    context-path: /
    encoding:
      force: true
      charset: utf-8
      enabled: true
#    session:
#      timeout: 30m # 默认失效30分钟
#      cookie:
#        path: / #cook存放路径为根目录,实现同域名,不同项目的session共享

version: @project.version@

spring:
  profiles:
    active: prod
  #  resources:
  #  不要为我们工程中的资源文件建立映射,会拦截所有页面 home.html
  #    add-mappings: false
  mvc:
    #出现错误时, 直接抛出异常
    #    throw-exception-if-no-handler-found: true
    # 小logo
    static-path-pattern: /**

  servlet:  #上传文件
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
      resolve-lazily: false
  datasource:
    name: ax_shop
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/ax_shop?characterEncoding=utf-8&useSSL=false
    #    schema 定时器 自动执行sql语句
    #    schema:
    #      - classpath:sql/test.sql
    #    schema 一定要加
    filters: stat,wall,log4j

    #    #druid相关配置
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙    /druid 后台管理
      filters: stat,wall
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 配置监控服务器
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        reset-enable: false
        url-pattern: /druid/*
        # 添加IP白名单
        #allow:
        # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
        #deny:
      web-stat-filter:
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

  redis:
    host: localhost # Redis服务器地址
    password:   # Redis服务器连接密码（默认为空）
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    #    lettuce:
    #      pool:
    #        max-active:
    #    pool:
    #      max-idle: 8 # 连接池中的最大空闲连接
    #      min-idle: 0 # 连接池中的最小空闲连接
    #      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
    #      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 5000 # 连接超时时间（毫秒）\

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  sql:
    init:
      mode: ALWAYS
#  quartz:
#    properties:
#      org:
#        quartz:
#          scheduler:
#            instanceName: clusteredScheduler
#            instanceId: AUTO
#          jobStore:
#            class: org.quartz.impl.jdbcjobstore.JobStoreTX
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#            tablePrefix: QRTZ_
#            isClustered: false
#            clusterCheckinInterval: 10000
#            useProperties: false
#          threadPool:
#            class: org.quartz.simpl.SimpleThreadPool
#            threadCount: 10
#            threadPriority: 5
#            threadsInheritContextClassLoaderOfInitializingThread: true
#    job-store-type: jdbc

# Shiro相关配置
shiro:
  user:
    # 登录地址
    loginUrl: /login.do
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /home
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: -1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ax.mall.entity
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰
    database-id: ax_mysql
#    cache-enabled: true #开启二级缓存



#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

logging:
  #  file:
  #    path:
  #  config: classpath:log4j2.xml
  level:
    com.ax.mall.mapper: debug
#    com.ax: info
swaggerEnabled: false