server:
  servlet:
    context-path: /
    encoding:
      force: true
      charset: utf-8
      enabled: true
#    session:
#      timeout: 30m # 默认失效30分钟
#      cookie:
#        path: / #cook存放路径为根目录,实现同域名,不同项目的session共享

version: @project.version@

spring:
  profiles:
    active: prod

  thymeleaf:
    mode: HTML # 模板的模式
    cache: false # 这个开发配置为false，避免改了模板还要重启服务器
    check-template-location: true # 检查模板是否存在，然后再呈现
    enabled: true #启用MVC Thymeleaf视图分辨率
    template-resolver-order: 0
    suffix: .html
    prefix: classpath:/templates/ # 这个是配置模板路径的，默认就是templates，可不用配置
    encoding: UTF-8


# Shiro相关配置
shiro:
  user:
    # 登录地址
    loginUrl: /login.do
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /home
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: -1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ax.mall.entity
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰
    database-id: ax_mysql
#    cache-enabled: true #开启二级缓存



#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

logging:
  #  file:
  #    path:
  #  config: classpath:log4j2.xml
  level:
    com.ax.mall.mapper: debug
#    com.ax: info
swaggerEnabled: false