version: 1.0.0


axing:
  config:
    username: jim
    password: 1234
  person:
    id: 1

#user:
#  list:
#    - username: user1
#      password: 132456
#    - username: user222
#      password: 132456




