server:
  port: 9003
  servlet:
    context-path: /payment

spring:
  application:
    name: demo07-nacos-payment
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.101.135:8848
