spring:
  profiles:
    active: dev
  aop:
    proxy-target-class: true

thread:
  pool:
    core-size: 100 #核心线程数
    max-size: 500 #最大线程数
    keepalive: 60 #空闲线程存活时间
    block-queue-size: 1000 #等待队列长度
