server:
  port: 9002

spring:
  application:
    name: demo12-nacos-order-consumer #订单作为消费者
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
server-url:
  nacos-payment-service: http://demo12-nacos-payment
