server:
  port: 8080
  servlet:
    context-path: /
spring:
  profiles:
    include:
      swagger
  application:
    name: minio-demo

minio:
  endpoint: http://localhost:9030
  access-key: admin #访问的key
  secret-key: admin123 #访问的秘钥
axing:
  base-packages: com.ax
