server:
  port: 8090

spring:
  application:
    name: demo12spring-cloud-alibaba-sentinel
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
      datasource:
        nacos:
          serverAddr: localhost:8848
          dataId: ${spring.application.name}
          groupId: DEFAULT_GROUP
          data-type: json
          rule-type: flow
          username: nacos
          password: nacos

