server:
  port: 8700

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/ax_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

secure:
  ignored:
    urls: #安全路径白名单
      - /
      # swagger
      - /swagger-ui.html
      - /swagger-ui/
      - /swagger-resources/**
      - /v3/api-docs/**

      # 静态资源
      - /*.html
      - /favicon.ico
      - /**/*.html
      - /**/*.css
      - /**/*.js
      - /**/*.png
      - /favicon.ico

      # 接口
      - /admin/login

      # 第三方服务
      - /actuator/**
      - /druid/**

# 注解方式
springdoc:
  api-docs:
    #是否开启文档功能
    enabled: true
    #swagger后端请求地址
  #    path: /api-docs
#  swagger-ui:
  #自定义swagger前端请求路径，输入http：127.0.0.1:8080/test会自动重定向到swagger页面
  #    path: /test
  #包扫描路径
  #  packages-to-scan: com.axing.controller
  #这里定义了两个分组，可定义多个，也可以不定义
  group-configs:
    #分组名
    - group: admin
      display-name: admin接口
      #按路径匹配
      paths-to-match: /admin/**
    - group: brand
      #按路径匹配
      paths-to-match: /brand/**

axing:
  response:
    base-packages: com.axing.security