spring:
  datasource:
    driver-class-name: net.sourceforge.jtds.jdbc.Driver
    url: jdbc:jtds:sqlserver://192.168.101.137:1433;DatabaseName=AIS20220215152257
    username: witsoft
    password: witsoft@xp
    hikari:
      connection-test-query: SELECT 1


mybatis-flex:
  global-config:
    print-banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
