spring:
  data:
    # 这2个方式都可以
    mongodb:
      host: 47.101.156.93
      port: 27017
      authentication-database: admin
      database: ax_demo
      username: root
      password: '123456' #如果是纯数字，需要加个单引号
#      uri: mongodb://root:123456@47.101.156.93:27017/ax_demo?authSource=admin
