#springdoc:
#  api-docs:
#    path: api
# 最大支持文件大小

spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      # 最大支持请求大小
      max-request-size: 1000MB

axing:
  response:
    base-packages: com.axing.demo27

doc-info:
  title: 测试项目1

logging:
  level:
#    root: debug
    com.axing.demo27: debug
  config: classpath:logback-spring.xml
  file:
    path: logs
#    DEBUG
#    ERROR
#    FATAL
#    INFO
#    OFF
#    TRACE
#    WARN