# 端口
server:
  port: 8070
#开放端点用于SpringBoot Admin的监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: admin-client # 给client应用取个名字
  boot:
    admin:
      client:
        url: http://localhost:8090   #这里配置admin server 的地址

logging:
  config: classpath:logback-spring.xml
  file:
    path: /logs
    name: /logs/${spring.application.name}/info.log,
