server:
  port: 8092

spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: / #虚拟机
    username: admin
    password: admin
    # 手动确认消息
    listener:
      simple:
        acknowledge-mode: manual # 手动确认
#        prefetch: 1 # 设置每一个消费端能够处理未确认消息的最大数，默认是250,一般用默认的就行了，这里是测试我们用1
