server:
  port: 11060

spring:
  application:
    name: cloud-stream-producer

  rabbitmq:
    host: 192.168.101.135
    port: 5672  #mq调用的端口为5672
    username: admin
    password: admin
    virtual-host: /

    publisher-returns: true   #开启 return 确认机制
    publisher-confirm-type: correlated #return 确认机制类型
    template:
      mandatory: true #设置为true后消费者在消息没有被路由到合适队列情况下会被return监听，而不会自动删除

  cloud:
    stream:
#      default-binder: test-rabbit
#      binders:
#        test-rabbit:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                host: 192.168.101.135
#                port: 5672
#                username: admin
#                password: admin
#                virtual-host: /

#      rabbit:
#        bindings:
#          delayed-out-0:
#            producer:
#              delayed-exchange: true


      #      default-binder: rabbit
#      binders: #自此处配置要绑定的rabbitmq的服务信息
#        msn-binder: #表示定义的名称，用于binding整合
#          type: rabbit #消息组件类型
#          # 这里配置环境,好处,可以有多个rabbitmq环境
#          environment: # 设置rabbitmq的相关的环境配置 stream3.1只需要配置这些即可
#            spring:
#              rabbitmq:
#                host: localhost
#                port: 5672  #mq调用的端口为5672
#                username: admin
#                password: 123456
#                virtual-host: my_vhost

      bindings:
        order-out-0:
          destination: mq.order

        cluster-out-0:
          destination: cluster-topic

        broadcast-out-0:
          destination: broadcast-topic

        delayed-out-0:
          destination: delayed-topic

