server:
  port: 9002

spring:
  application:
    name: demo07-nacos-order #订单作为消费者
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
server-url:
  nacos-payment-service: http://demo07-nacos-payment
