server:
  port: 9002
  servlet:
    context-path: /order

spring:
  application:
    name: demo07-nacos-order #订单作为消费者
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.101.135:8848
server-url:
  nacos-payment-service: http://demo07-nacos-payment
  gateway-service: http://nacos-gateway-main
