server:
  servlet:
    context-path: /
  port: 11014

spring:
  application:
    name: redis-demo
  jackson:
    date-format: yyyy年MM月dd日 HH:mm:ss
  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 1800000     # 缓存默认有效时长，以毫秒为单位
  #  data:
  #    redis:
  #      host: 192.168.101.135 # Redis服务器地址
  #      password: 123456  # Redis服务器连接密码（默认为空）
  #      database: 11 # Redis数据库索引（默认为0）
  #      port: 6379 # Redis服务器连接端口
  #      timeout: 5000 # 连接超时时间（毫秒）\
  #      lettuce:
  #        pool:
  #          max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
  #          min-idle: 0  # 连接池中的最小空闲连接
  #          max-idle: 8 # 连接池中的最大空闲连接
  #          max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
  redis:
    host: 192.168.101.135 # Redis服务器地址
    password: 123456 # Redis服务器连接密码（默认为空）
    database: 1 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    timeout: 5000 # 连接超时时间（毫秒）\
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        min-idle: 0  # 连接池中的最小空闲连接
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）

#    redisson:
#      config:
#        classpath: redisson.yml

axing:
  #  response:
  #    base-packages: com.axing.demo
  redis:
    save-package-name: true
  doc:
    title: redis测试项目



